### ISSUE TITLE
Array for data-hidden-buttons?

### ISSUE THREAD

**Issue by mwsasser** [toopay/bootstrap-markdown#154]
Shouldn't this work in the `textarea` tag?  

`data-hidden-buttons="['cmdImage','cmdUrl']"`

I'm only a hobby developer so it's possible I'm misunderstanding how to put an array into the tag properly.  But I have tried these also:

`data-hidden-buttons="[cmdImage,cmdUrl]"`
`data-hidden-buttons="'cmdImage','cmdUrl'"`
`data-hidden-buttons="cmdImage,cmdUrl"`

**Comment by abelorian** [comment]
+1

**Comment by mwsasser** [comment]
I only want to hide the url and image.  But any information on how to put it in an array properly would be nice.

**Comment by phenyll** [comment]
In case this Question is still relevant:

you can use data-hidden-buttons='["cmdHeading","cmdImage"]'
seen here: http://stackoverflow.com/a/6071653/936304

this is because this plugin is using standard jquery calls to parse the settings.
you can find the code here: https://github.com/toopay/bootstrap-markdown/blob/master/js/bootstrap-markdown.js#L36

**Comment by nicklayb** [comment]
You don't need to put an array. I searched in the source as I was looking for the same feature and it appears that it splits the value by space " ". So you can just do it that way :

`data-hidden-buttons="cmdPreview cmdHeading"`

**Comment by lodev09** [comment]
I think this will work if you want a "proper" html format:
`data-hidden-buttons="[&quot;cmdHeading&quot;,&quot;cmdImage&quot;]"`

Basically the value should be in `JSON` format so it needs quotes :)
