### ISSUE TITLE
Edit While Previewing, WYSIWYG Style

### ISSUE THREAD

**Issue by Panman8201** [toopay/bootstrap-markdown#156]
I'm looking for more of a WYSIWYG editor that saves markdown "behind the scenes". This looks like a nice editor for bootstrap but you can't edit while in Preview mode. Not sure if this is out-of-scope for the project, but it would be perfect for my needs!

**Comment by lodev09** [comment]
In that case, this plugin is not for you since bootstrap-markdown is an editor for markdown. In your case, I would suggest to look for WYSIWYG plugin then refer to their API. What you would do is grab the HTML while/after editing and use [this plugin](https://github.com/domchristie/to-markdown) to convert HTML to markdown and save it.

**Comment by squasher83** [comment]
**Ala ma kota**
_A kot ma ale_

> 

- `No`

 i co teraz
