### ISSUE TITLE
Feature request: Editing on the Preview view

### ISSUE THREAD

**Issue by AnderUstarroz** [toopay/bootstrap-markdown#172]
You made an awesome work here guys, but in terms of usability would be much nicer por the users being able to just write and set the styles without needing to see that bold is "**" or any other code conversion. Same way as if they are simply writing a word document.

**Comment by toopay** [comment]
Thanks for the kind word @AnderUstarroz. But since this library was intended for markdown, its inevitable to not seeing those markdown syntax. I believe its possible to make it behave as common WYSIWYG editor, but thats will make this library bloated - and i dont like bloated code.

The viable solution for you is to utilize available hooks, and made inline preview next to your editor element.
